# base OS setup

---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - htop
      - net-tools
      - ca-certificates
      - gnupg
      - lsb-release
      - ufw
    state: present

- name: Allow SSH in UFW
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow node_exporter in UFW
  community.general.ufw:
    rule: allow
    port: "9100"
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
